dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - cppcheck
    - docbook-xml
    - docbook-xsl
    - libxml2-utils
    - linux-libc-dev
    - xsltproc
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- cppcheck --error-exitcode=1 *.c
- make
- xmllint --nonet --noout --valid doc/*.xml
- make doc

# vim:ts=2 sts=2 sw=2 et
